language: go
go:
- 1.8.x

before_install:
- go get github.com/mitchellh/gox
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install stable

install:
- go get github.com/gin-gonic/gin
- go get github.com/sirupsen/logrus
- go get github.com/gorilla/websocket

script:
- mkdir -p ./dist/static/dist

# Build golang
- gox -osarch="linux/amd64" -output "./dist/{{.Dir}}"

# Build the UI
- cd ./ui
- npm install
- npm run build
- cp ./dist/build.js ../dist/static/dist
- cp index.html ../dist/static
- pwd # /home/travis/gopath/src/github.com/retocode/openshift-cross-cluster-loadbalancer/ui
- cd ..
- pwd # /home/travis/gopath/src/github.com/retocode/openshift-cross-cluster-loadbalancer
- ls
- ls dist/

# Pack the smart load balancer
- tar -zcvf smart-load-balancer.tar.gz dist/openshift-cross-cluster-loadbalancer dist/static/index.html dist/static/dist

deploy:
  provider: releases
  api_key:
    secure: hleCoh7Mauc3dS9rWPUy1563z6E4ZOlz63Z40b2pEXrtUCVLaTdOKVT7fGkpqcjxXqdaS97QR1mzTgXUtu1PSu7Fm+N1pSaqru3NP6bYax+1SLx+SMQOV7LTmIO9T/9Uia8WTZ44K0g7kW5o6YF+pMJx0NKSdbFM4lNS/XcRRojlHswlLg0gsITzjqddHYNdXDdSgYRUw7A2DJ0lSGwoxhiY+NH7CEA+322GoU/RFEoO0z/obvJxjVEQExNpVtY7kG2PdsDVhoIQjq3rBVZY+JQIPS5t5FRTnkLJ+1IQz9WjKPMu3++THnpahXzWbUQw3eGTI10qNO4FtoTbhDVkDupH03x4PiXafGJQWYGVfjB48PuNN01MmsFISFlaMnI6qEQmxVGtcX2tsppOP6USI90plYPLygtPQbc8k8BXpBbxCx63SCWz5hJsJxXOJgGROCA8hIoDZhl/1ShtdqIBZPXS20Ez5/of03lWI5+Vdjdp9v/QbkTMF3P4DFRg6qqZdUQR0M8bT9vqoXtwTbaOhjRnZ36SkNHUiSaXrbbT4W8aEu+peRsJD3cvYYcjpEdULs6ffYFifPbFozEvBjmtc00/Ecz2QnJ5id89w9n/Y8kOBf9sXM1T6BbN3Q37CKL/w14phlVYCMQ3hCHiOQz+f7no7MOAUf7L5ui6WE8+6lU=
  file: smart-load-balancer.tar.gz
  skip_cleanup: true
  on:
    tags: true