language: go
go:
- 1.8.x

before_install:
- go get github.com/mitchellh/gox
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install stable

install:
- go get github.com/gin-gonic/gin
- go get github.com/sirupsen/logrus
- go get github.com/gorilla/websocket

script:
- mkdir -p ./dist/static/dist

# Build golang
- gox -osarch="linux/amd64" -output "./dist/{{.Dir}}" github.com/retocode/openshift-cross-cluster-loadbalancer

# Build the UI
- cd ./ui
- npm install
- npm run build
- cp ./dist/build.js ../../dist/static/dist
- cp index.html ../../dist/static
- pwd # /home/travis/gopath/src/github.com/retocode/openshift-cross-cluster-loadbalancer/ui
- cd ..
- pwd # /home/travis/gopath/src/github.com/retocode/openshift-cross-cluster-loadbalancer
- ls
- ls dist/

# Pack the smart load balancer
- tar -zcvf smart-load-balancer.tar.gz dist/openshift-cross-cluster-loadbalancer dist/static/index.html dist/static/dist

deploy:
  provider: releases
  api_key:
    secure: aUPqkwrlK4xps/e9NipGHQ/9UxuHNS2ygXiDV6f3+H4als67/yzEJ54CIKmY2B7WseA86HHtKh56Eh4W56a+uM/DJAxsPfS8c8igpXy8YVe2g4LwZ3u1HGrsfBcf5+X0X+o8K71I2OFiy7gkZGXKAf45yQLATn+O9dwJrxy119JkCqGPrg6LJ8AEi7btTAARlyRLgYoudBmuMjUifO+YDE4MMKBTPx1g84wCL5z+Eu6JFzUEsiE/aNvfHr7hTjCBdhZW9UseOcYAR8XJ5zksRj1rHP6rbQ2vkm7fmlSAnLypdD7my4jnSgJ4wzj9Qg4OrlNVW735Y5FuT9RmOWKzrk1X7fNavdNjyhmZZO86bb02iEzS3igCKAqX7+0KJdj7ZUTYLCGoFoW6HU6sotQtWPOVPcXjt+Ozpo4F4iKiaK5TI3aS8TRXZAdwHE27ZBbly6cwtUSQ5xknB9xVlLhuwghqvesELT6ALJfwe6h0Ou4g6vn4lJLwu4PxmL6vTUZ8CGLGVu+8rfBHcZp8SROzzp/F9SSgjkdUY0p29eHuHi1TfA5dSJooZ4Lul/FhkDe4tp7waqP3b7VA33xLHkY9alE8An6xh/x0gCA91vwgm0Ib39l86aNmBdAJlusxkTWoB/B1rpu45MXsw567zX/oX1sArr9e3LNxzUujr+v4yRY=
  file:
  - smart-load-balancer.tar.gz
  skip_cleanup: true
  on:
    tags: true